cost:
  # Safety DDP parameters
  COST_TYPE: Reachability
  # SAFETY COST PARAM
  W_ctrl: [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001]
  MAX_VELOCITY: [5.0, 4.0, 4.0, 4.0, 15.0, 15.0, 15.0, 15.0, 15.0, 15.0, 15.0, 15.0, 15.0, 15.0]
  SMOOTHING_TEMP: 3.0

solver:
  N: 25
  MAX_ITER: 10
  MAX_ITER_RECEDING: 200
  # Line search options: 'baseline'.
  # Baseline seems to be good enough for most cases.
  LINE_SEARCH: 'baseline'
  # Filter options: 'none', 'LR', 'CBF'
  FILTER_TYPE: 'CBF'
  CONSTRAINT_TYPE: 'linear'
  CBF_GAMMA: 0.9
  SOFT_CBF_GAMMA: 0.9
  LR_THRESHOLD: 0.0
  #unused
  OUT_FOLDER: exps_may/ilqr/ant/reachability_experiment_mulobs_config1/

