cost:
  # Safety DDP parameters
  COST_TYPE: Reachability
  # SAFETY COST PARAM
  W_1: 0.01
  W_2: 0.01
  MAX_ANGULAR_VELOCITY: [5.0, 5.0]
  MAX_TARGET_ANGULAR_VELOCITY: [5.0, 5.0]
  SMOOTHING_TEMP: 2.0

solver:
  N: 20
  MAX_ITER: 20
  MAX_ITER_RECEDING: 100
  # Line search options: 'baseline'.
  # Baseline seems to be good enough for most cases.
  LINE_SEARCH: 'baseline'
  # Filter options: 'none', 'LR', 'CBF'
  FILTER_TYPE: 'CBF'
  CONSTRAINT_TYPE: 'linear'
  CBF_GAMMA: 0.9
  SOFT_CBF_GAMMA: 0.9
  LR_THRESHOLD: 0.0
  #unused
  OUT_FOLDER: exps_may/ilqr/reacher/reachability_experiment_mulobs_config1/

