cost:
  # Safety DDP parameters
  COST_TYPE: Reachability
  # SAFETY COST PARAM
  W_1: 0.05
  W_2: 0.05
  MAX_ANGULAR_VELOCITY: [11.0, 11.0]
  SMOOTHING_TEMP: 2.0

solver:
  N: 20
  MAX_ITER: 20
  MAX_ITER_RECEDING: 100
  # Line search options: 'baseline'.
  # Baseline seems to be good enough for most cases.
  LINE_SEARCH: 'baseline'
  # Filter options: 'none', 'LR', 'CBF'
  FILTER_TYPE: 'SoftCBF'
  CBF_TYPE: 'quadratic'
  CBF_GAMMA: 0.99
  SOFT_CBF_GAMMA: 0.99
  LR_THRESHOLD: 0.0
  OUT_FOLDER: exps_may/ilqr/pvtol6D/reachability_experiment_mulobs_config1/

